import mrok

MROK_VERSION_TAG_NAME = "mrok"
MROK_VERSION_TAG_VALUE = mrok.__version__
MROK_VERSION_TAG = {MROK_VERSION_TAG_NAME: MROK_VERSION_TAG_VALUE}
MROK_SERVICE_TAG_NAME = "mrok-service"
MROK_IDENTITY_TYPE_TAG_NAME = "mrok-identity-type"
MROK_IDENTITY_TYPE_TAG_VALUE_INSTANCE = "instance"
MROK_IDENTITY_TYPE_TAG_VALUE_PROXY = "proxy"
